// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd3G6bIO9tJ9SNorbc7uZXS9qxOSiJf28',
    appId: '1:922425962648:web:5f6d7a1ccc68d05700a0ed',
    messagingSenderId: '922425962648',
    projectId: 'lab-visitas',
    authDomain: 'lab-visitas.firebaseapp.com',
    storageBucket: 'lab-visitas.appspot.com',
    measurementId: 'G-94V5LVQEYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJdn8B5c5470uAt0UYZ36Y_PrBpIUzw8',
    appId: '1:922425962648:android:9aafea69d4a86c5600a0ed',
    messagingSenderId: '922425962648',
    projectId: 'lab-visitas',
    storageBucket: 'lab-visitas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtu7w7N2SFHVn3xPnEw2N2gJ-jPLJvcos',
    appId: '1:922425962648:ios:f74b6ce5334bdc9a00a0ed',
    messagingSenderId: '922425962648',
    projectId: 'lab-visitas',
    storageBucket: 'lab-visitas.appspot.com',
    iosClientId: '922425962648-a3vo9ljfhsirvl51hhfp4h0as8dnotei.apps.googleusercontent.com',
    iosBundleId: 'com.example.labVisitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtu7w7N2SFHVn3xPnEw2N2gJ-jPLJvcos',
    appId: '1:922425962648:ios:f74b6ce5334bdc9a00a0ed',
    messagingSenderId: '922425962648',
    projectId: 'lab-visitas',
    storageBucket: 'lab-visitas.appspot.com',
    iosClientId: '922425962648-a3vo9ljfhsirvl51hhfp4h0as8dnotei.apps.googleusercontent.com',
    iosBundleId: 'com.example.labVisitas',
  );
}
